services:
  - type: web
    name: ppoker
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    domains:
      - ppoker-s944.onrender.com  # Replace with your preferred domain
